// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOIDfw1_7LBH8i69I4oVxYloGdzU0-lw',
    appId: '1:783459693324:web:179800659c7c7888578f29',
    messagingSenderId: '783459693324',
    projectId: 'dhainventory-2337e',
    authDomain: 'dhainventory-2337e.firebaseapp.com',
    storageBucket: 'dhainventory-2337e.appspot.com',
    measurementId: 'G-6FNVY2200Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJxKjkKRd8ft5HJXDYBcrogygCcKRyt8',
    appId: '1:783459693324:android:1da7f5b0e2f0f1bc578f29',
    messagingSenderId: '783459693324',
    projectId: 'dhainventory-2337e',
    storageBucket: 'dhainventory-2337e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSiYV5GEAAQvlbQNp8V4eIPn_7nsIMpI',
    appId: '1:783459693324:ios:2729ead9cd36a525578f29',
    messagingSenderId: '783459693324',
    projectId: 'dhainventory-2337e',
    storageBucket: 'dhainventory-2337e.appspot.com',
    iosBundleId: 'com.inventory.dha',
  );
}
